spring.application.name=api-gateway

server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator
management.endpoints.web.exposure.include=*

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# STARTUP SERVICE
spring.cloud.gateway.routes[2].id=startup-service
spring.cloud.gateway.routes[2].uri=lb://STARTUP-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/startups/**