spring.application.name=startup-service

spring.application.name=STARTUP-SERVICE
server.port=8084

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/startup_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/