-- V1__init_auth_schema.sql
CREATE TABLE users (id BIGSERIAL PRIMARY KEY, email VARCHAR UNIQUE NOT NULL, password VARCHAR NOT NULL, role VARCHAR NOT NULL, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE refresh_tokens (id BIGSERIAL PRIMARY KEY, email VARCHAR NOT NULL, token VARCHAR NOT NULL, expiry_date TIMESTAMP);
