ALTER TABLE startup ADD COLUMN IF NOT EXISTS tagline VARCHAR(255);
ALTER TABLE startup ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE startup ADD COLUMN IF NOT EXISTS founded_year INTEGER;
ALTER TABLE startup ADD COLUMN IF NOT EXISTS team_size INTEGER DEFAULT 0;
ALTER TABLE startup ADD COLUMN IF NOT EXISTS mrr DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE startup ADD COLUMN IF NOT EXISTS stage VARCHAR(100);
