ALTER TABLE startup
    ADD COLUMN IF NOT EXISTS equity_offered DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS website_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(500);
